### ISSUE TITLE
 The VM failed to remain in the "running" state while attempting to boot.

### ISSUE THREAD

**Issue by mhenke** [bdcravens/railo-vagrant#8]
```
The VM failed to remain in the "running" state while attempting to boot.
This is normally caused by a misconfiguration or host system incompatibilities.
Please open the VirtualBox GUI and attempt to boot the virtual machine
manually to get a more informative error message.
```

http://whatan00b.com/virtualbox-and-subsequently-vagrant-machines-fail-to-boot

I tried reload like mentioned https://github.com/myplanetdigital/vagrant-ariadne but didn't work

**Comment by mhenke** [comment]
I opened up virtual machine. Then on the vagrant instance when to Settings -- System -- Motherboard -- checked Enable EFI (special OSes only)

Now the vagrant vm starts in Oracle Virtual machine.

I try vagrant up. It seems to work but hangs.

**Comment by bdcravens** [comment]
What is the host OS? What version of Vagrant and VirtualBox do you have installed?

**Comment by mhenke** [comment]
http://the.0gravity.co.uk/universe/vagrant/

Vagrant sometimes hangs on "Waiting for VM to boot. This can take a few minutes" which was a problem I ran into building your own box seems to help. However if you don't want to do that, switching the Vagrant config to enable GUI mode and logging in from VirtualBox and running "sudo dhclient" sorts it out.

**Comment by mhenke** [comment]
Hey Bill :-) Xubuntu 12.10, VB  4.2.6, V 1.0.6

This project looks cool. Have you seen Deploy Rails book? Covers this stuff. Reading it now

**Comment by bdcravens** [comment]
Is Xubuntu on bare metal, or inside a VM itself?

**Comment by mhenke** [comment]
bare metal

**Comment by mhenke** [comment]
not reproducible
